title: DIVIDED/ATTENTION
description: Thoughts on tech, home, and everything in between
url: "https://dividedattn.com"
baseurl: ""
permalink: /:title/

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
